id: P8300CAF2
initial_creation_type: input
source_metadata:
  title: Khenpo Kunzang Palden Series
  language: bo
  description: 'Texts by and about Khenpo Kunzang Palden (kun bzang dpal ldan, 1862–1943),
    alias Khenpo Kunpal, an important disciple of Patrul Rinpoche and author of a
    celebrated commentary on the Bodhicaryāvatāra:'
  volume:
    b3d9e07128a74cde993ddb3a8d030ece:
      title: 'Lightning Bands of Compassion: A Song of Lament for Khenchen Kunzang
        Palden Tupten Chökyi Drakpa'
      parent: Songs
created_at: '2022-03-01T00:25:56.628023'
last_modified_at: '2022-03-01T00:25:56.628025'
